In [67]:
from sklearn.metrics import cohen_kappa_score
import numpy as np
import pandas as pd

In [46]:
a = np.array([[20,5],[15,10]])
tot = np.sum(a)

p_observed = (agg[0][0] + agg[1][1])/ tot 
p_yes = ((agg[0][0] + agg[0][1]) / tot) * ((agg[0][0] + agg[1][0]) / tot) 
p_no = ((agg[1][0] + agg[1][1]) / tot) * ((agg[0][1] + agg[1][1]) / tot) 
p_expected = p_yes + p_no

k = (p_observed - p_expected) / (1 - p_expected)

print(f"confusion matrix:\n {a}")
print(f"n observations: {tot}")
print(f"p_observed: {p_observed}")
print(f"p_yes: {p_yes}")
print(f"p_no: {p_no}")
print(f"k: {k}")

confusion matrix:
 [[20  5]
 [15 10]]
n observations: 50
p_observed: 0.7
p_yes: 0.3
p_no: 0.2
k: 0.3999999999999999


In [62]:
a = np.array([[85, 5],[3,7]])
tot = np.sum(a)

p_observed = (a[0][0] + a[1][1])/ tot 
p_yes = ((a[0][0] + a[0][1]) / tot) * ((a[0][0] + a[1][0]) / tot) 
p_no = ((a[1][0] + a[1][1]) / tot) * ((a[0][1] + a[1][1]) / tot) 

p_expected = p_yes + p_no

k = (p_observed - p_expected) / (1 - p_expected)

print(f"confusion matrix:\n {a}")
print(f"n observations: {tot}")
print(f"p_observed: {p_observed}")
print(f"p_yes: {p_yes}")
print(f"p_no: {p_no}")
print(f"k: {k}")

confusion matrix:
 [[85  5]
 [ 3  7]]
n observations: 100
p_observed: 0.92
p_yes: 0.792
p_no: 0.012
k: 0.5918367346938777


In [65]:
a = np.array([[80, 10],[8,2]])
tot = np.sum(a)

p_observed = (a[0][0] + a[1][1])/ tot 
p_yes = ((a[0][0] + a[0][1]) / tot) * ((a[0][0] + a[1][0]) / tot) 
p_no = ((a[1][0] + a[1][1]) / tot) * ((a[0][1] + a[1][1]) / tot) 

p_expected = p_yes + p_no

k = (p_observed - p_expected) / (1 - p_expected)

print(f"confusion matrix:\n {a}")
print(f"n observations: {tot}")
print(f"p_observed: {p_observed}")
print(f"p_yes: {p_yes}")
print(f"p_no: {p_no}")
print(f"k: {k}")

confusion matrix:
 [[80 10]
 [ 8  2]]
n observations: 100
p_observed: 0.82
p_yes: 0.792
p_no: 0.012
k: 0.08163265306122401


In [108]:
rater1_A = [1] * 30 + [0] * 70
rater2_A = [1] * 22 + [0] * 70 + [1] * 8

rater1_B = [0] * 45  + [1] * 10 + [0] * 45
rater2_B = [1] * 2 + [0] * 90 +[1] * 8

df = pd.DataFrame({'rater1_A':rater1_A, 
                   'rater2_A':rater2_A,
                   'rater1_B':rater1_B, 
                   'rater2_B':rater2_B,})

df['rater1_AB'] = [1 if x > 0 else 0 for x in df['rater1_A'] + df['rater1_B']]
df['rater2_AB'] = [1 if x > 0 else 0 for x in df['rater2_A'] + df['rater2_B']]

# df.head()

print(f"Agree on A: {cohen_kappa_score(df['rater1_A'], df['rater2_A'], )}")
print(f"Agree on B: {cohen_kappa_score(df['rater1_B'], df['rater2_B'], )}")
print(f"Agree on AB: {cohen_kappa_score(df['rater1_AB'], df['rater2_AB'], )}")

Agree on A: 0.6190476190476191
Agree on B: -0.11111111111111116
Agree on AB: 0.4347826086956522
